apiVersion: batch/v1
kind: CronJob
metadata:
  name: heliumevents-trawler-james
  namespace: heliumevents
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: heliumevents-trawler
            image: rdomloge/heliumevents:4.2.0
            imagePullPolicy: IfNotPresent
            env:
            - name: HOTSPOT
              value: "112KVEvBawFScQeXgmzLGAZLG3mAozQFchig3NzPKBi5FYKvQGdk"
            - name: ES_SERVER_ADDRESS
              value: "http://elasticsearch-service:9200"
            - name: USE_STAKEJOY_API
              value: "false"
            - name: spring.main.banner-mode
              value: "off"
            - name: "ENCODE_TIMESTAMPS"
              value: "true"
          restartPolicy: OnFailure
          tolerations:
            - key: "cpu"
              operator: "Equal"
              value: "low"
            - key: "memory"
              operator: "Equal"
              value: "low"
              
              
