apiVersion: batch/v1
kind: CronJob
metadata:
  name: heliumevents-trawler-crp
  namespace: heliumevents
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: heliumevents-trawler
            image: rdomloge/heliumevents:4.2.0
            imagePullPolicy: Always
            env:
            - name: HOTSPOT
              value: "112Xa4p36ExdVDktAPFKx9zd8EwiMw7vC35hxyqiiYANC527BLiF"
            - name: ES_SERVER_ADDRESS
              value: "http://elasticsearch-service:9200"
            - name: spring.main.banner-mode
              value: "off"
            - name: USE_STAKEJOY_API
              value: "false"
            - name: "logging.level.com.domloge"
              value: "INFO"
          restartPolicy: OnFailure
