apiVersion: batch/v1
kind: CronJob
metadata:
  name: activity-james
  namespace: heliumevents
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  schedule: "0 */6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: heliumevents-trawler
            image: rdomloge/heliumevents:2.0.2
            imagePullPolicy: IfNotPresent
            env:
            - name: HOTSPOT
              value: "112KVEvBawFScQeXgmzLGAZLG3mAozQFchig3NzPKBi5FYKvQGdk"
            - name: ES_SERVER_ADDRESS
              value: "http://elasticsearch-service:9200"
            - name: USE_STAKEJOY_API
              value: "true"
          restartPolicy: OnFailure