apiVersion: batch/v1
kind: CronJob
metadata:
  name: heliumevents-trawler-davey
  namespace: heliumevents
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: heliumevents-trawler
            image: rdomloge/heliumevents:2.0.2
            imagePullPolicy: IfNotPresent
            env:
            - name: HOTSPOT
              value: "11idBCdgeGRv15HYxWXQ4Vnrs1V5RAsubTs7poRYjVPM3Zgv2HZ"
            - name: ES_SERVER_ADDRESS
              value: "http://elasticsearch-service:9200"
            - name: USE_STAKEJOY_API
              value: "false"
          restartPolicy: OnFailure
