apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: heliumevents
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
      version: v1
  template:
    metadata:
      labels:
        app: kibana
        version: v1
    spec:
      containers:
        - name: kibana
          image: kibana:7.14.2
          imagePullPolicy: IfNotPresent
          env:
            - name: "ELASTICSEARCH_HOSTS"
              value: "http://elasticsearch-service:9200"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"
          ports:
            - containerPort: 5601
              name: http