apiVersion: v1
kind: PersistentVolume
metadata:
  name: heliumevents-data
spec:
  capacity:
    storage: 20Gi
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 10.0.0.60
    path: "/volume1/heliumevents"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: heliumevents-config
spec:
  capacity:
    storage: 1Mi
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 10.0.0.60
    path: "/volume1/heliumevents/config"
