kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: heliumevents-data
  namespace: heliumevents
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
